apps/web/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import (home, create_account, aplicativo, user_logout)

app_name = 'web'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^create_account$', create_account, name='create_account'),
    url(r'^aplicativo$', aplicativo, name='aplicativo'),
    url(r'^user_logout$', user_logout, name='user_logout'),
]

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from apps.web import urls as web_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(web_urls, namespace='web')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/web/aplicativo.html
{% load static %}
<html>
<head>
    <title>Kasperu | Aplicativo</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <!-- Include the above in your HEAD tag -->

    <link rel="stylesheet" type="text/css" href="{% static '' %}css/home.css">
    <link rel="stylesheet" type="text/css" href="{% static '' %}css/login.css">
    <script type="text/javascript" src="{% static '' %}js/aplicativo.js"></script>

    <!-- js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<header>
    {% if request.user.is_authenticated %}
        <div class="boton_logout">
            <a href="{% url 'web:user_logout' %}">
                <input type="button" value="Logout" class="logout"/>
            </a>
        </div>
    {% endif %}
</header>

<body>
<div class="container">
    <div class="col-md-8 col-md-offset-2">
    <h3>Ingrese el archivo csv</h3>
    <form method="POST" action="{% url 'web:aplicativo' %}" enctype="multipart/form-data" class="form_archivo">
        {% csrf_token %}
        <input type="hidden" name="tipo_form" value="form-1">
        <div class="form-group">
            <div class="input-group input-file" name="Fichier1">
                <span class="input-group-btn">
                    <button class="btn btn-default btn-choose" type="button">Choose</button>
                </span>
                <input type="text" class="form-control" id="archivo_form" name="archivo" {% if not flag_archivo %} placeholder='Choose a file...' {% else %} placeholder="{{archivo_text}}"  {% endif %}  class="validate[required]"/ >
                <span class="input-group-btn">
                     <button class="btn btn-warning btn-reset" type="button">Reset</button>
                </span>
            </div>
        </div>
        <br>
        <button class="btn btn-primary carga"> Cargar/Limpiar </button>
        {% if archivo %}
            <button type="button" class="btn btn-success mostrar_csv_2"> Visualizar 50 primera filas </button>

        <button type="button" class="btn btn-warning mostrar_histogramas_2"> Generar Histogramas </button>
        <button class="btn btn-warning mostrar_3m_2"> Generar Media, Mediana y la Moda </button>
        {% endif %}

    </form>

    <form class="form-muestra-archivo" method="POST" action="{% url 'web:aplicativo' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="Fichier1" value="{{archivo}}">
        <input type="hidden" name="tipo_form" value="form-2">
        <button type="submit" class="btn btn-success mostrar_csv" style="display:none"> Visualizar 50 primera filas </button>
    </form>
    <!-- 50 rows -->

    <div class="container-fluid">
        <div class="table-responsive"></div>
            <table class="table table-bordered table-hover table-condensed">

            {% for row in lista_general %}
                <tr{% if forloop.first%} class="success" {%endif %}>
                    <td>{{row.0}}</td>
                    <td>{{row.1}}</td>
                    <td>{{row.2}}</td>
                    <td>{{row.3}}</td>
                    <td>{{row.4}}</td>
                    <td>{{row.5}}</td>
                </tr>
            {% endfor %}
            {% for row in rango %}
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            {% endfor %}
            </table>
    </div>
    <!-- Histogramas -->

    <form class="form-muestra-histogramas" method="POST">
        {% csrf_token %}
        <input type="hidden" name="tipo_form" value="form-3">
        <button style="display:none" class="btn btn-warning mostrar_histogramas"> Generar Histogramas </button>
    </form>

    <form class="form-3m" method="POST">
        {% csrf_token %}
        <input type="hidden" name="tipo_form" value="form-4">
        <button style="display:none" class="btn btn-warning mostrar_3m"> Generar Media, Mediana y la Moda </button>
        {% if flag_form_4 %}
            <div class="container-fluid">
                <div class="table-responsive"></div>
                    <table class="table table-bordered table-hover table-condensed">
                        <tr class="success">
                            <td>&nbsp;</td>
                            <td>Edad</td>
                            <td>Peso</td>
                            <td>Estatura</td>
                        </tr>
                        <tr{% if forloop.first%} class="success" {%endif %}>
                            <td>Media</td>
                            <td>{{edades_media}}</td>
                            <td>{{pesos_media}}</td>
                            <td>{{estaturas_media}}</td>
                        </tr>
                        <tr>
                            <td>Mediana</td>
                            <td>{{edades_mediana}}</td>
                            <td>{{pesos_mediana}}</td>
                            <td>{{estaturas_mediana}}</td>

                        </tr>
                        <tr>
                            <td>Moda</td>
                            <td>{{edades_mode}}</td>
                            <td>{{pesos_mode}}</td>
                            <td>{{estaturas_mode}}</td>

                        </tr>
                    </table>
            </div>
        {% endif %}
    </form>

    </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.validationEngine-es.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.validationEngine.js' %}"></script>
<script type="text/javascript">
$(function(){
    $("form").validationEngine('attach', {
        promptPosition : "topLeft",
        autoHidePrompt: true,
        autoHideDelay: 3000,
        binded: false,
        scroll: false
    });

    $('.carga').click(function(e){
        e.preventDefault();
        var valid = $('.form_archivo').validationEngine('validate');
        if(valid){       
            $('.form_archivo').submit()
        }
    })
    $('.mostrar_csv').click(function(e){
        e.preventDefault();
        $('.form-muestra-archivo').submit()

    })
    $('.mostrar_csv_2').click(function(e){
        console.log("A");       
        $('.mostrar_csv').click();
    })

    $('.mostrar_histogramas').click(function(e){
        e.preventDefault();
        $('.form-muestra-histogramas').submit();
    })
    $('.mostrar_histogramas_2').click(function(e){
       // e.preventDefault();
        //$('.mostrar_histogramas').click();
    })
    $('.mostrar_3m').click(function(e){
        e.preventDefault();
        $('.form-3m').submit();
    })
    $('.mostrar_3m_2').click(function(e){
        e.preventDefault();
        $('.mostrar_3m').click();
    })
    $('.btn-reset').click(function(e){
        e.preventDefault();
        $('#archivo_form').attr('placeholder', "Seleccione un archivo por favor :) ")
    })
    
})
</script>
</body>
</html>

templates/web/create_account.html
{% load static %}
<html>
<head>
	<title></title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

	<!-- Include the above in your HEAD tag -->

	<link rel="stylesheet" type="text/css" href="{% static '' %}css/home.css">

    <!-- js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
	<div>
	   <div class="modal-dialog">
			<div class="loginmodal-container">
			<h1>Crear una cuenta</h1><br>
			<form method="POST" action="{% url 'web:create_account' %}" class="form-log">
				{% csrf_token %}
				<input type="text" name="email" placeholder="Correo" class="validate[required]">
				<input type="password"  id="password" name="password" placeholder="Password" class="validate[required]">
				<input type="password" id="confirm_password" name="password" placeholder="Repetir Password" class="validate[required,equals[password]]">

				<input type="submit" class="login loginmodal-submit" value="Crear cuenta">

			</form>
						
				<div class="login-help">
					¿Ya tienes cuenta?<a href=""></a> - <a href="{% url 'web:home' %}" style="color: #0067b8">Ingresar</a>
				</div>
			</div>
		</div>
	</div>
<script type="text/javascript" src="{% static 'js/jquery.validationEngine-es.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.validationEngine.js' %}"></script>
<script type="text/javascript">
$(function(){
	$("form").validationEngine('attach', {
		promptPosition : "topLeft",
		autoHidePrompt: true,
		autoHideDelay: 3000,
		binded: false,
		scroll: false
	});

    $('.login').click(function(e){
        e.preventDefault();
		var valid = $('.form-log').validationEngine('validate');
		if(valid){
			$('.form-log').submit()
		}
        
    })
})
</script>
</body>
</html>

templates/web/home.html
{% load static %}
<html>
<head>
	<title></title>
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

	<!-- Include the above in your HEAD tag -->

	<link rel="stylesheet" type="text/css" href="{% static '' %}css/home.css">

</head>
<body>
	<div>
	   <div class="modal-dialog">
			<div class="loginmodal-container">
			<h1>KasPeru Login</h1><br>
			<form class="form-login" method="POST" action="{% url 'web:home' %}">
				{% csrf_token %}
				<input type="text" name="email" placeholder="Correo Electronico" class="validate[required]">
				<input type="password" name="password" placeholder="Password" class="validate[required]">
				<input type="submit" name="login" class="login loginmodal-submit" value="Login">
			</form>
						
				<div class="login-help">
					¿No tiene una cuenta?<a href=""></a> - <a href="{% url 'web:create_account' %}" style="color: #0067b8">Crear una</a>
				</div>
			</div>
		</div>
	</div>
<script type="text/javascript" src="{% static 'js/jquery.validationEngine-es.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.validationEngine.js' %}"></script>
<script type="text/javascript">
$(function(){
	$("form").validationEngine('attach', {
		promptPosition : "topLeft",
		autoHidePrompt: true,
		autoHideDelay: 3000,
		binded: false,
		scroll: false
	});

    $('.login').click(function(e){
        e.preventDefault();
		var valid = $('.form-login').validationEngine('validate');
		if(valid){
			$('.form-login').submit()
		}
        
    })
})
</script>
</body>

</html>